### PR TITLE
Friendship v2

### PR DESCRIPTION
**Pull request by ioilmio**
This PR adds:
-mutual friendship feature;
-helpers tests;
-refactor show view;
-post create test;

### CODE REVIEW

**Review by uryelah — CHANGES_REQUESTED** [review]
Hi **Isabirye Isabirye & Salvo Illuminato**, I'm Sarah your reviewer for this PR 👩‍🚀 

The mutual friendships are pretty cool, but sadly you didn't implement the main focus of this milestone: double friendship rows.

Please re-read the requirements for this milestone and then check the required changes below carefully.

# Required Changes 🏗️ 🐛 💡

- [ ] when friendship is confirmed, an additional row with reversed user-friend pair is created (
 thanks to this, we can find user friends only by user_id in the friendships table).
ex:
```ruby 
def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end

```

- [ ] Your timeline posts method currently has a lot of application logic written at the controller, you can achieve the same result with a simpler approach like:
```ruby
  Post.where(user: (user.friends + user))
# The above will get posts from user and from all users in user.friends
```

- [ ] Please add updated tests, models and requests, after you make the changes in the application logic.

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [x] Let's implement changes as requested by the previous TSE about timeline post.
- [ ]  Instead of processing objects in application memory, let's define association with SQL query.
````ruby
# confirm friends
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships

# pending_friends
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend

#friend_requests
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships

`````

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General
- [ ] You should add an accept button here.



- [ ] Am getting multiple requests from one user, Let's fix that.


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi **TEAM**, congratulations on a great job :fireworks: Having fixed all the comments made by the previous TSE's, I hereby approve the project :+1: 

Go ahead and merge into development
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Pull request merged**
